image: Visual Studio 2017

configuration:
  - Release

before_build:
- curl -LO https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip
- unzip SFML-2.5.1-windows-vc15-64-bit.zip
- mv SFML-2.5.1 SFML